name: Build Base Packer Images
on:
  workflow_dispatch
#  push:
#    branches:
#      - master
#    paths:
#      - 'resources/**'
#      - 'scripts/**'

jobs:
  build_image:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1
      - name: Setup base images
        run: |
          cd scripts && sh ./build_images.sh